// <auto-generated />
namespace OnlineShop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class product_config : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(product_config));
        
        string IMigrationMetadata.Id
        {
            get { return "201608090323373_product_config"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
